### ISSUE TITLE
gallery-dl_hook.lua is not working on Windows

### ISSUE THREAD

**Issue by phanirithvij** [jgreco/mpv-scripts#3]
Hi, I used your gallery-dl lua script but it doesn't work.

command
```
mpv gallery-dl://https://imgur.com/gallery/7AtGJJg
```

Error message:
```shell
λ mpv gallery-dl://https://imgur.com/gallery/7AtGJJg
Cannot find main.* for any supported scripting backend in: C:\Users\Rithvij\AppData\Roaming/mpv/scripts/others
Cannot find main.* for any supported scripting backend in: C:\Users\Rithvij\AppData\Roaming/mpv/scripts/mpv-scripts
[gallery_dl_hook] Traceback (most recent call last):
[gallery_dl_hook]   File "c:\users\rithvij\appdata\local\programs\python\python38\lib\runpy.py", line 192, in _run_module_as_main
[gallery_dl_hook]     return _run_code(code, main_globals, None,
[gallery_dl_hook]   File "c:\users\rithvij\appdata\local\programs\python\python38\lib\runpy.py", line 85, in _run_code
[gallery_dl_hook]     exec(code, run_globals)
[gallery_dl_hook]   File "C:\Users\Rithvij\AppData\Local\Programs\Python\Python38\Scripts\gallery-dl.exe\__main__.py", line 7, in <module>
[gallery_dl_hook]   File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\gallery_dl\__init__.py", line 112, in main
[gallery_dl_hook]     output.replace_std_streams()
[gallery_dl_hook]   File "c:\users\rithvij\appdata\local\programs\python\python38\lib\site-packages\gallery_dl\output.py", line 153, in replace_std_streams
[gallery_dl_hook]     stream.buffer,
[gallery_dl_hook] AttributeError: 'NoneType' object has no attribute 'buffer'
[gallery_dl_hook] failed to get album list.
[playlist] Reading plaintext playlist.
Warning: empty playlist
No protocol handler found to open URL gallery-dl://https://imgur.com/gallery/7AtGJJg
The protocol is either unsupported, or was disabled at compile-time.


Exiting... (Errors when loading file)
```

**Comment by phanirithvij** [comment]
gallery-dl is downloading the images from the gallery normally when using

```shell
gallery-dl https://imgur.com/gallery/7AtGJJg
``` 

And

```shell
λ gallery-dl.exe -g https://imgur.com/a/7AtGJJg
https://i.imgur.com/sUWPlCL.png
https://i.imgur.com/MsXOF90.png
https://i.imgur.com/aHFeZJe.png
https://i.imgur.com/HHyTd7i.png
https://i.imgur.com/8B95XmK.png
https://i.imgur.com/3kS88XJ.png
https://i.imgur.com/twleH7a.png
https://i.imgur.com/HlTMB9U.png
https://i.imgur.com/u6uGJsY.png
https://i.imgur.com/9ML4Csl.png
https://i.imgur.com/c8vj8Na.png
https://i.imgur.com/thrIFE5.png
https://i.imgur.com/vgjUCdt.png
https://i.imgur.com/AqWAj4u.png
https://i.imgur.com/04pmPk1.png
https://i.imgur.com/tzigNb7.png
https://i.imgur.com/zDfW42L.png
```

**Comment by phanirithvij** [comment]
My Os is windows.
It seems to be an issue with gallery-dl itself.
I've posted an issue https://github.com/mikf/gallery-dl/issues/653.

**Comment by phanirithvij** [comment]
It's fixed in the updated gallery-dl version.
